name: Run tests with tox

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Not all Python versions are available for linux AND x64
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, '3.10', '3.11.0-beta - 3.11',
                         'pypy-3.7', 'pypy-3.8', 'pypy-3.9']
        extra: ['', '-smtp']
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: tox -vv -e py${{ matrix.extra }}
